Buyer/urls.py
from django.urls import path,include,re_path
from Buyer.views import *
from django.views.decorators.cache import cache_page

urlpatterns = [
    # path('Saller/',include('Saller.urls')),
    path('login/',login),
    path('index/',index),
    path('register/',register),
    path('base/',base),
    path('logout/',logout),
    # path('goods_list/',cache_page(60*15)(goods_list)),
    path('goods_list/',goods_list),
    re_path('goods_list/(?P<page>\d+)',goods_list),
    re_path('detail/(?P<id>\d+)',detail),
    path('user_center_info/',user_center_info),
    path('user_center_order/',user_center_order),
    path('place_order/',place_order),
    path('place_order_more/',place_order_more),
    path('alipayviews/',AlipayViews),
    path('payresult/',payresult),
    path('add_cart/',add_cart),
    path('cart/',cart),
    # path('cache_test/',cache_test),
    path('reqtest/',reqtest),
    path('process_tem_rep/',process_tem_rep),

]

Qshop/urls.py
from django.contrib import admin
from django.urls import path,include,re_path
from Buyer.views import index


urlpatterns = [
    path('admin/', admin.site.urls),
    path('Saller/',include('Saller.urls')),
    path('Buyer/',include('Buyer.urls')),
    re_path('^$',index),

]

Buyer/models.py
from django.db import models
from Saller.models import *
# Create your models here.


ORDER_STATUS={
    (0,'未支付'),
    (1,'已支付'),
    (2,'已发货'),
    (3,'已完成'),
    (4,'拒绝发货'),
}
# 订单表
class PayOrder(models.Model):
    order_number = models.CharField(max_length=32,verbose_name='订单编号',unique=True)
    order_date = models.DateField(auto_now=True,verbose_name='订单日期')
    # 订单状态 ：0-未支付  1-已支付  2-代发货 3-待收货 4-完成  5-拒收
    order_status = models.IntegerField(choices=ORDER_STATUS,verbose_name='订单状态')
    order_total = models.FloatField(verbose_name='订单总价')
    order_user = models.ForeignKey(to=LoginUser,on_delete=models.CASCADE,verbose_name='订单用户')  # 外键  连接到用户表


# 订单详情表
class OrderInfo(models.Model):
    order_id = models.ForeignKey(to=PayOrder,on_delete=models.CASCADE,verbose_name='订单编号')
    goods = models.ForeignKey(to=Goods,on_delete=models.CASCADE,verbose_name='订单商品')
    goods_price = models.FloatField(verbose_name='商品单价')# 指下单时商品的单价
    goods_count = models.IntegerField(verbose_name='商品数量')
    goods_total_price = models.FloatField(verbose_name='商品小计')
    store_id = models.ForeignKey(to=LoginUser,on_delete=models.CASCADE,verbose_name='店铺id')
    status = models.IntegerField(choices=ORDER_STATUS,default=0)


class Cart(models.Model):

    goods_number = models.IntegerField(verbose_name='商品数量')
    goods_price = models.FloatField(verbose_name='商品单价')
    goods_total = models.FloatField(verbose_name='商品总价')
    goods = models.ForeignKey(to=Goods,on_delete=models.CASCADE)
    cart_user = models.ForeignKey(to=LoginUser,on_delete=models.CASCADE)
    order_number = models.CharField(max_length=32,default=0)
    # goods_delete = models.IntegerField(default=0) # 0-不删除  1-删除

class UserAddress(models.Model):
    user_name = models.CharField(max_length=32)
    user_address = models.TextField()
    user_code = models.CharField(max_length=32)
    user_phone = models.CharField(max_length=11)
    status = models.IntegerField(default=0)
    user = models.ForeignKey(to=LoginUser,on_delete=models.CASCADE)

Buyer/views.py
from django.shortcuts import render
from Saller.models import *
from Buyer.models import *
from django.http import HttpResponseRedirect,HttpResponse,JsonResponse
import hashlib
from django.core.paginator import Paginator
import time
from alipay import AliPay
from Qshop.settings import alipay_private_key_string,alipay_public_key_string
import logging
collect = logging.getLogger('django')
# Create your views here.

def LoginVaild(func):
    def inner(request,*args,**kwargs):
        username = request.COOKIES.get('username')
        # 获取session
        session_username = request.session.get('username')
        if username and session_username and username == session_username:
            return func(request,*args,**kwargs)
        else:
            return HttpResponseRedirect('/Buyer/login/')
    return inner
def setPassword(password):
    md5 = hashlib.md5()
    md5.update(password.encode())
    result = md5.hexdigest()

    return result

# from django.views.decorators.cache import cache_page
# @cache_page(60*20)  # 视图中使用缓存，缓存寿命20分钟
def index(request):
    # goods = GoodsType.objects.all()
    goods_type = GoodsType.objects.all()
    goods_list = Goods.objects.all()
    result = []
    for type in goods_type:
        goods = type.goods_set.order_by('-goods_price')
        if len(goods) >= 4:
            goods = goods[:4]
            result.append({'type':type,'goods':goods})
    # 构建一个返回数据类型  返回满足4条的商品，有4条商品的类型
    return render(request,'buyer/index.html',locals())

def login(request):
    if request.method == 'POST':
        error_msg = ''
        email = request.POST.get('email')
        password = request.POST.get('pwd')
        if email:
            user = LoginUser.objects.filter(email=email,user_type=1).first()
            if user:
                # 存在
                if user.password == setPassword(password):
                    # 登录成功
                    # 跳转页面
                    # return HttpResponseRedirect('/index/')
                    response = HttpResponseRedirect('/Buyer/index/')
                    response.set_cookie('username', user.username)
                    response.set_cookie('user_id', user.id)
                    request.session['username'] = user.username  # 设置session
                    collect.info('%s is login'% user.username)
                    return response
                else:
                    error_msg = '密码错误'
            else:
                error_msg = '用户不存在'
        else:
            error_msg = '邮箱不可以为空'
    return render(request,'buyer/login.html',locals())
def logout(request):
    # 删除cookie  删除session
    response = HttpResponseRedirect('/Buyer/login/')
    # response.delete_cookie('kname')
    keys = request.COOKIES.keys()
    for one in keys:
        response.delete_cookie(one)
    del request.session['username']
    return response
def register(request):
    if request.method == 'POST':
        error_msg=''
        email = request.POST.get('email')
        password = request.POST.get('password')
        if email:
            # 判断邮箱是否存在
            loginuser = LoginUser.objects.filter(email=email).first()
            print(loginuser)
            if not loginuser:
                #不存在 写库
                user = LoginUser()
                user.email = email
                user.username = email
                user.password = setPassword(password)
                user.save()
                return HttpResponseRedirect('/Buyer/login/')
            else:
                error_msg = '邮箱已经被注册，请登录'
        else:
            error_msg = '邮箱不可以为空'
    return render(request,'buyer/register.html',locals())

def base(request):
    return render(request,'buyer/base.html')

def goods_list(request,page=1):
    """
    req_type  完成判断请求
        当req_type=search
            keywords商品名字
        当req_type = findall
            keywords 传递商品类型id，寻求该类型下的商品
    :param request:
    :return:
    """
    page = int(page)
    keywords = request.GET.get('keywords')
    req_type = request.GET.get('req_type')
    if req_type == 'findall':
        # 查看更多
        print(keywords)
        goods_type = GoodsType.objects.get(id = keywords)
        goods = goods_type.goods_set.all()

    elif req_type == 'search':
        # 搜索功能
        goods = Goods.objects.filter(goods_name__contains=keywords).all()
    end = len(goods)//5
    end += 1
    recommend = goods.order_by('-goods_pro_time')[:end]

    page_all = Paginator(goods,4)
    page_list = page_all.page(page)
    print(page_list)
    # return HttpResponse(page)

    # goods = Goods.objects.all()
    # recommend = Goods.objects.order_by("-goods_pro_time")
    return render(request,"buyer/goods_list.html",locals())

def detail(request,id):
    goods = Goods.objects.get(id=int(id))
    return render(request,'buyer/detail.html',locals())

@LoginVaild
def user_center_info(request):
    return render(request,'buyer/user_center_info.html',locals())

# 订单页面
@LoginVaild
def place_order(request):

    # 保存订单
    goods_id = request.GET.get('goods_id')
    goods_count = request.GET.get('goods_count')
    user_id = request.COOKIES.get('user_id')

    if goods_id and goods_count:
        goods_id = int(goods_id)
        goods_count = int(goods_count)
        goods = Goods.objects.get(id=goods_id)
        # 保存订单表
        payorder = PayOrder()
        order_number = str(time.time()).replace('.','')
        payorder.order_number = order_number # 订单编号
        payorder.order_status = 0
        payorder.order_total = goods.goods_price * goods_count
        payorder.order_user = LoginUser.objects.get(id = user_id)
        payorder.save()

        # 保存订单详情表

        orderinfo = OrderInfo()
        orderinfo.order_id = payorder
        orderinfo.goods = goods
        orderinfo.goods_count = goods_count
        orderinfo.goods_price = goods.goods_price
        orderinfo.goods_total_price = goods.goods_price * goods_count
        orderinfo.store_id = goods.goods_store
        orderinfo.save()
    # 订单数量




        total_count = 0
        all_goods_info = payorder.orderinfo_set.all()
        for one in all_goods_info:
            total_count += one.goods_count




    # 商品id
    # 生产订单编号





    return render(request,'buyer/place_order.html',locals())


def AlipayViews(request):
    order_id = request.GET.get('order_id') # 订单id
    payorder = PayOrder.objects.get(id=order_id)
    # 实例化支付对象
    alipay = AliPay(
        appid='2016101300673955',
        app_notify_url=None,
        app_private_key_string=alipay_private_key_string,
        alipay_public_key_string=alipay_public_key_string,
        sign_type="RSA2",
    )
    # 实例化订单
    order_string = alipay.api_alipay_trade_page_pay(
        subject='天天生鲜',  # 交易主体
        out_trade_no=payorder.order_number,  # 订单号
        total_amount=str(payorder.order_total),  # 交易总金额
        return_url='http://127.0.0.1:8000/Buyer/payresult/',  # 请求支付，之后及时回调的一个接口
        notify_url='http://127.0.0.1:8000/Buyer/payresult/'  # 通知地址
    )

    # 发送支付请求
    # 请求地址  支付网关 + 实例化订单
    result = 'https://openapi.alipaydev.com/gateway.do?' + order_string

    return HttpResponseRedirect(result)

def payresult(request):
    # 通过get获取支付宝传递参数，获取其中的订单号，修改订单的状态
    order_number = request.GET.get('out_trade_no')
    print(order_number)
    payorder = PayOrder.objects.get(order_number=order_number)
    payorder.order_status = 1
    payorder.save()
    return render(request,'buyer/payresult.html',locals())


# 添加购物车
def add_cart(request):
    """
    使用post请求，完成添加购物车功能
    :param request: goods_id  count
    :return:
    """
    result = {'code':10001,'msg':''}
    if request.method == 'POST':
        goods_id = request.POST.get('goods_id')
        count = float(request.POST.get('count',1))
        user_id = request.COOKIES.get('user_id')

        goods = Goods.objects.get(id=goods_id)
        cart = Cart()
        cart.goods_number = count
        cart.goods_price = goods.goods_price
        cart.goods_total = cart.goods_price*cart.goods_number
        cart.goods = goods
        cart.cart_user = LoginUser.objects.get(id=user_id)
        cart.save()
        result['code'] = 10000
        result['msg'] = '添加购物车成功'
    else:
        result['code'] = 10001
        result['msg']='请求方式不正确'


    return HttpResponse(result)

@LoginVaild
def cart(request):

    user_id = request.COOKIES.get('user_id')
    # 查询购物车中商品
    cart_list = []
    cart = Cart.objects.filter(cart_user_id=user_id).order_by('-id') # 倒序
    count = cart.count()  # 获取条数
    for one in cart:
        if one.order_number != '0':
            # 说明有订单号  订单状态不为已支付
            payorder = PayOrder.objects.get(order_number=one.order_number)
            if payorder.order_status != 1:
                # 已支付订单
                cart_list.append(one)
            else:
                count -= 1
        else:
            cart_list.append(one)


    return render(request,'buyer/cart.html',locals())

def place_order_more(request):
    data = request.GET
    userid = request.COOKIES.get('user_id')
    # 区分 通过获取前端get请求的参数，找到goods_id和对应的数量
    # startswith  以goods开始的key
    data_item = data.items()
    request_data = []
    for key,value in data_item:
        # print('%s-----%s'%(key,value))
        if key.startswith('goods'):
            goods_id = key.split('_')[1]
            count = request.GET.get('count_'+goods_id)
            cart_id = key.split('_')[2]
            request_data.append((int(goods_id),int(count),int(cart_id)))


    if request_data:
        payorder = PayOrder()
        order_number = str(time.time()).replace('.', '')
        payorder.order_number = order_number  # 订单编号
        payorder.order_status = 0
        payorder.order_total = 0
        payorder.order_user = LoginUser.objects.get(id = userid)

        order_total = 0
        total_count = 0
        payorder.save()
        # 订单详情   保存多条，一种商品一条数据
        for goods_id_one,count_one,cart_id in request_data:
            # 遍历到一条订单中的多个商品的id和对应的数量
            goods = Goods.objects.get(id=goods_id_one)

Buyer/templates/buyer/base.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
	<title>{% block title %}{% endblock %}</title>
	<link rel="stylesheet" type="text/css" href="/static/buyer/css/reset.css">
	<link rel="stylesheet" type="text/css" href="/static/buyer/css/main.css">
	<script type="text/javascript" src="/static/buyer/js/jquery-1.12.4.min.js"></script>
	<script type="text/javascript" src="/static/buyer/js/jquery-ui.min.js"></script>
	<script type="text/javascript" src="/static/buyer/js/slide.js"></script>
    {% block style %}{% endblock %}
</head>

<body>
	<div class="header_con">
		<div class="header">
			<div class="welcome fl">欢迎来到天天生鲜!</div>
			<div class="fr">
				<div class="login_info fl">
					欢迎您：<em>{{ request.COOKIES.username }}</em>
				</div>
				<div class="login_btn fl">
                    {% if request.COOKIES.username %}
                        <a href="#">欢迎{{ request.COOKIES.username }}</a>
                        <a href="/Buyer/logout/">退出</a>
                    {% else %}
                        <a href="/Buyer/login/">登录</a>
					    <span>|</span>
					    <a href="/Buyer/register/">注册</a>
                    {% endif %}

				</div>
				<div class="user_link fl">
					<span>|</span>
                    {% if request.COOKIES.username %}
					<a href="/Buyer/user_center_info/">用户中心</a>
					<span>|</span>
					<a href="/Buyer/cart/">我的购物车</a>
					<span>|</span>
					<a href="/Buyer/user_center_order/">我的订单</a>
                    {% endif %}
				</div>
			</div>
		</div>
	</div>

	<div class="search_bar clearfix">
		<a href="/Buyer/index/" class="logo fl"><img src="/static/buyer/images/logo.png"></a>
		<div class="search_con fl">
			<input type="text" class="input_text fl" name="" placeholder="搜索商品" id="keywords">
			<input type="button" class="input_btn fr" name="" value="搜索" onclick="getgoods()">
		</div>
		<div class="guest_cart fr">
			<a href="/Buyer/cart/" class="cart_name fl">我的购物车</a>
			<!--<div class="goods_count fl" id="show_count">1</div>-->
		</div>
	</div>
    

    {% block content %}

    {% endblock %}

	<div class="footer">
		<div class="foot_link">
			<a href="#">关于我们</a>
			<span>|</span>
			<a href="#">联系我们</a>
			<span>|</span>
			<a href="#">招聘人才</a>
			<span>|</span>
			<a href="#">友情链接</a>
		</div>
		<p>CopyRight © 2016 北京天天生鲜信息技术有限公司 All Rights Reserved</p>
		<p>电话：010-****888    京ICP备*******8号</p>
	</div>
    {% block script %}

    {% endblock %}
	<script type="text/javascript" src="/static/buyer/js/slideshow.js"></script>
    <script type="text/javascript">
        function getgoods(){
            keywords = $('#keywords').val();
            if (keywords){
                url = "/Buyer/goods_list/?keywords="+keywords+'&req_type=search';
                window.location.href=url;
            }
        }
    </script>
	<script type="text/javascript">
		BCSlideshow('focuspic');
		var oFruit = document.getElementById('fruit_more');
		var oShownum = document.getElementById('show_count');

		var hasorder = localStorage.getItem('order_finish');

		if(hasorder)
		{
			oShownum.innerHTML = '2';
		}

		oFruit.onclick = function(){
			window.location.href = 'list.html';
		}
	</script>


</body>

</html>

Buyer/templates/buyer/cart.html
{% extends 'buyer/base.html' %}
{% block title %}
    天天生鲜-购物车
{% endblock %}
{% block content %}
    <div class="total_count">全部商品<em>{{ cart.count }}</em>件</div>
	<ul class="cart_list_th clearfix">
		<li class="col01">商品名称</li>
		<li class="col02">商品单位</li>
		<li class="col03">商品价格</li>
		<li class="col04">数量</li>
		<li class="col05">小计</li>
		<li class="col06">操作</li>
	</ul>
    <form action="/Buyer/place_order_more">
        {% for one in cart_list %}
            <ul class="cart_list_td clearfix">
            <li class="col01"><input class="goods_check" type="checkbox" name="goods_{{ one.goods.id }}_{{ one.id }}"></li>
            <li class="col02"><img src="/static/{{ one.goods.picture }}"></li>
            <li class="col03">{{ one.goods.goods_name }}<br><em>{{ one.goods_price }}/500g</em></li>
            <li class="col04">500g</li>
            <li class="col05">{{ one.goods_price }}元</li>
            <li class="col06">
                <div class="num_add">
                    <a href="javascript:;" class="add fl">+</a>
                    <input type="text" class="num_show fl" value="{{ one.goods_number }}" name="count_{{ one.goods.id }}">
                    <a href="javascript:;" class="minus fl">-</a>
                </div>
            </li>
            <li class="col07">{{ one.goods_total }}元</li>
            <li class="col08"><a href="javascript:;">删除</a></li>
        </ul>
        {% endfor %}




        <ul class="settlements">
            <li class="col01"><input type="checkbox" name="" id="boxall"></li>
            <li class="col02">全选</li>
            <li class="col03">合计(不含运费)：<span>¥</span><em id="total_mount">0.0</em><br>共计<b id="total_number">0</b>件商品</li>
            <li class="col04"><input style="display:block;height:78px;width:168px;background-color:#ff3d3d;text-align:center;line-height:78px;color:#fff;font-size:24px" type="submit" value="去结算"></li>
        </ul>
    </form>
{% endblock %}

{% block script %}
    <script>
    $("#boxall").click(
        function(){

            {#console.log(this.checked);// 得到this指向的对象有没有checked属性#}
            //this.checked  返回 true 选中   false  没有选中  没有checked属性
            //当选中的时候，增加goods_check   checked属性
            //当不选中的时候，去掉goods_check 的checker属性

            if(this.checked){
                //当条件为true的时候   全选
                $('.goods_check').prop('checked',true);
            }else{
                //当条件为false的时候   全选
                $('.goods_check').prop('checked',false);
            }
            add()
        }
    )

    $(".goods_check").each(
        function(){
            $(this).click(
                function(){
                    if(!this.checked){
                //$("#boxall").prop('checked',true);
             //}else{
                        $("#boxall").prop('checked',false);
                    }
                    add()
                }
            )
        }
    );

    function add() {
        // 完成方法
        // 获取选中的商品的数量和小计
        // 计算出商品的总数量和总价
        // 给元素赋值
        var dic = {num:0,total:0};
        $(".goods_check").each(
            function(){
                // 拿到循环的每一条，判断是否有checked属性，获取有checked属性的小计和数量
                if(this.checked){
                    // 被选中的
                    var num = parseInt($(this).parents(".cart_list_td").find(".num_show").val());  // 数量
                    var total = parseFloat($(this).parents(".cart_list_td").find(".col07").text()); // 小计
                    dic.num += num;
                    dic.total += total;

                }
            }
        )
        $("#total_mount").text(dic.total);
        $("#total_number").text(dic.num);
    }


    </script>
{% endblock %}

Buyer/templates/buyer/goods_list.html
{% extends "buyer/base.html" %}
{% block title%}
    商品列表
{% endblock %}

{% block content %}
    <div class="navbar_con">
		<div class="navbar clearfix">
			<div class="subnav_con fl">
				<h1>全部商品分类</h1>
				<span></span>
				<ul class="subnav">
					<li><a href="#" class="fruit">新鲜水果</a></li>
					<li><a href="#" class="seafood">海鲜水产</a></li>
					<li><a href="#" class="meet">猪牛羊肉</a></li>
					<li><a href="#" class="egg">禽类蛋品</a></li>
					<li><a href="#" class="vegetables">新鲜蔬菜</a></li>
					<li><a href="#" class="ice">速冻食品</a></li>
				</ul>
			</div>
			<ul class="navlist fl">
				<li><a href="">首页</a></li>
				<li class="interval">|</li>
				<li><a href="">手机生鲜</a></li>
				<li class="interval">|</li>
				<li><a href="">抽奖</a></li>
			</ul>
		</div>
	</div>

    <div class="breadcrumb">
		<a href="#">全部分类</a>
		<span>></span>
		<a href="#">新鲜水果</a>
	</div>
    {% if goods %}
        <div class="main_wrap clearfix">
		<div class="l_wrap fl clearfix">
			<div class="new_goods">
				<h3>新品推荐</h3>
				<ul>
                    {% for one in recommend %}
					<li>
						<a href="/Buyer/detail/{{ one.goods_store_id }}"><img src="/static/{{ one.picture }}"></a>
						<h4><a href="#">{{ one.goods_name }}</a></h4>
						<div class="prize">￥{{ one.goods_price }}</div>
					</li>
                       {% endfor %}

				</ul>
			</div>
		</div>

		<div class="r_wrap fr clearfix">
			<div class="sort_bar">
				<a href="#" class="active">默认</a>
				<a href="#">价格</a>
				<a href="#">人气</a>
			</div>

			<ul class="goods_type_list clearfix">
                {% for goods in page_list %}
				<li>
					<a href="/Buyer/detail/{{ goods.id }}"><img src="/static/{{ goods.picture }}"></a>
					<h4><a href="/detail/">{{ goods.goods_name }}</a></h4>
					<div class="operate">
						<span class="prize">￥{{ goods.goods_price }}</span>
						<span class="unit">16.80/500g</span>
						<a id="{{ goods.id }}" class="add_goods" title="加入购物车" onclick="add_cart(this)"></a>
					</div>
				</li>
                {% endfor %}

			</ul>
            <div class="pagenation" style="float: right;">

			{% for page in page_all.page_range %}
                <a href="/Buyer/goods_list/{{ page }}/?keywords={{ goods_type.id }}&req_type=findall" class="page-link">{{ page }}</a>
            {% endfor %}

            </div>
		</div>
	</div>
        {% else %}
        <p style="text-align: center; font-size: 30px;color: #a9aab1" >
            敬请期待^-^
        </p>
        <br>
        <p style="text-align: center;font-size: 15px;color: black">
            或许您需要：
            <a href="/Buyer/goods_list/?keywords=1&req_type=findall">苹果</a>
            <a href="/Buyer/goods_list/?keywords=2&req_type=findall">白菜</a>
            <a href="/Buyer/goods_list/?keywords=3&req_type=findall">猪肉</a>
        </p>
    {% endif %}

{% endblock %}

{% block script %}
    <script>
        function add_cart(obj){
            var goods_id = obj.id;
            console.log(goods_id);
            url = '/Buyer/add_cart/';
            send_data = {
                'goods_id':goods_id,
                'csrfmiddlewaretoken':'{{ csrf_token }}'
            };
            $.ajax(
                {
                    url:url,
                    type:"post",
                    data:send_data,
                    success:function(data){
                        console.log(data)
                    },
                    error:function(error){
                        console.log(error)
                    }

                }
            )
        }
    </script>
{% endblock %}

Buyer/templates/buyer/payresult.html
{% extends 'buyer/base.html' %}
{% block title %}
    支付结果
{% endblock %}
{% block content %}
    <div class="list_model">
        <h1>支付结果</h1>
        <table>
            {% for k,v in request.GET.items %}
                <tr>
                <th>{{ k }}:</th>
                <td>{{ v }}</td>
                </tr>
            {% endfor %}
        </table>
    </div>
{% endblock %}

Buyer/templates/buyer/user_center_order.html
{% extends 'buyer/base.html' %}
{% block title %}
    天天生鲜-用户中心
{% endblock %}
{% block content %}
    	<div class="main_con clearfix">
		<div class="left_menu_con clearfix">
			<h3>用户中心</h3>
			<ul>
				<li><a href="/Buyer/user_center_info">· 个人信息</a></li>
				<li><a href="/Buyer/user_center_order/" class="active">· 全部订单</a></li>
				<li><a href="user_center_site.html">· 收货地址</a></li>
			</ul>
		</div>
		<div class="right_content clearfix">
				<h3 class="common_title2">全部订单</h3>
                {% for one in payorder %}
                    <ul class="order_list_th w978 clearfix">
                        <li class="col01">{{ one.order_date }}</li>
                        <li class="col02">订单号：{{ one.order_number }}</li>
                        <li class="col02 stress">{{ one.get_order_status_display }}</li>


                    </ul>

                    <table class="order_list_table w980">
                        <tbody>
                            <tr>
                                <td width="55%">
                                    {% for order_info in one.orderinfo_set.all %}
                                    <ul class="order_goods_list clearfix">
                                        <li class="col01"><img src="/static/{{ order_info.goods.picture }}"></li>
                                        <li class="col02">{{ order_info.goods.goods_name }}<em>{{ order_info.goods_price }}元/500g</em></li>
                                        <li class="col03">{{ order_info.goods_count }}</li>
                                        <li class="col04">{{ order_info.goods_total_price }}元</li>
                                    </ul>
                                    {% endfor %}


                                </td>
                                <td width="15%">{{ one.order_total }}元</td>
                                <td width="15%">{{ one.get_order_status_display }}</td>
                                {% if one.order_status == 0 %}
                                    <td width="15%"><a href="/Buyer/alipayviews/?order_id={{ one.id }}" class="oper_btn">去付款</a></td>
                                {% else %}
                                    <td width="15%"><a href="#" class="oper_btn">查看物流</a></td>
                                {% endif %}

                            </tr>
                        </tbody>
                    </table>
                {% endfor %}



				<div class="pagenation">
					<a href="#">上一页</a>
					<a href="#" class="active">1</a>
					<a href="#">2</a>
					<a href="#">3</a>
					<a href="#">4</a>
					<a href="#">5</a>
					<a href="#">下一页></a>
				</div>
		</div>
	</div>
{% endblock %}